repos:
  - repo: local
    hooks:
      - id: uv-build
        name: uv build
        entry: uv build
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
